# Generated by Django 2.2.13 on 2020-07-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theaters', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screens',
            field=models.ManyToManyField(related_name='movies', through='theaters.Schedule', to='theaters.Screen'),
        ),
    ]
