# Generated by Django 2.2.13 on 2020-07-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_screens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.DurationField(help_text='<분:초>로 입력 - 예시: 90:00 (90분)'),
        ),
    ]
