# Generated by Django 2.2.13 on 2020-06-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, upload_to='trailers/'),
        ),
    ]
