# Generated by Django 2.2.13 on 2020-06-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.DurationField(help_text='<분:초>로 입력 - 예시: 90:00 (90분)'),
        ),
    ]
