# Generated by Django 2.2.14 on 2020-07-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200707_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='liked',
            new_name='raters',
        ),
    ]
