# Generated by Django 2.2.13 on 2020-07-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200701_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='close_date',
        ),
        migrations.AlterField(
            model_name='movie',
            name='grade',
            field=models.CharField(choices=[('all', '전체관람가'), ('12+', '12세이상관람가'), ('15+', '15세이상관람가'), ('18+', '청소년관람불가')], max_length=20),
        ),
    ]
