# Generated by Django 2.2.14 on 2020-07-11 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20200708_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['rank']},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='liked',
        ),
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='raters',
            field=models.ManyToManyField(related_name='rating_movies', through='movies.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MovieLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('liked_at', models.DateField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_likes', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_likes', to='movies.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='like_members',
            field=models.ManyToManyField(related_name='like_movies', through='movies.MovieLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
