# Generated by Django 2.2.13 on 2020-07-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200701_1734'),
        ('movies', '0003_auto_20200630_1616'),
    ]

    operations = [
    ]
