# Generated by Django 2.2.14 on 2020-07-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20200715_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_point_saved',
            field=models.BooleanField(default=False),
        ),
    ]
