# Generated by Django 2.2.14 on 2020-08-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20200811_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_num',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
