# Generated by Django 2.2.13 on 2020-06-28 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_screens'),
        ('theaters', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('00-10', '10시 이전'), ('10-13', '10시~13시'), ('13-16', '13시~16시'), ('16-18', '16시~18시'), ('18-21', '18시~21시'), ('21-00', '21시 이후')], max_length=20)),
                ('genre', models.ManyToManyField(related_name='profiles', to='movies.Genre')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ManyToManyField(related_name='profiles', to='theaters.Region')),
            ],
        ),
    ]
