# Generated by Django 2.2.13 on 2020-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200628_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
