# Generated by Django 2.2.14 on 2020-07-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200706_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='unique_id',
            field=models.TextField(blank=True),
        ),
    ]
