# Generated by Django 2.2.13 on 2020-07-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200705_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tier',
            field=models.CharField(choices=[('basic', 'BASIC'), ('vip', 'VIP')], default='basic', max_length=20),
        ),
    ]
