# Generated by Django 2.2.13 on 2020-07-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='movies.Movie')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='theaters.Region')),
            ],
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('impossible', '선택불가'), ('sit_apart', '띄어앉기석'), ('general', '일반'), ('disabled', '장애인석')], default='general', max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_types', to='theaters.Schedule')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_types', to='theaters.Seat')),
            ],
        ),
        migrations.CreateModel(
            name='SeatGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('adult', '성인'), ('youth', '청소년'), ('preferred', '우대')], default='adult', max_length=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_grades', to='reservations.Reservation')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_grades', to='theaters.Seat')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='reservation',
            field=models.ManyToManyField(related_name='seats', through='theaters.SeatGrade', to='reservations.Reservation'),
        ),
        migrations.AddField(
            model_name='seat',
            name='schedules',
            field=models.ManyToManyField(related_name='seats', through='theaters.SeatType', to='theaters.Schedule'),
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_type', models.CharField(choices=[('0', 'type_0'), ('1', 'type_1'), ('2', 'type_2')], default='0', max_length=20)),
                ('screen_type', models.CharField(choices=[('2D', '2D'), ('2Ds', '2D 자막'), ('3D', '3D')], default='2D', max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theaters.Theater')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='theaters.Screen'),
        ),
    ]
