# Generated by Django 2.2.14 on 2020-07-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='reservation',
            new_name='reservations',
        ),
        migrations.AlterField(
            model_name='seatgrade',
            name='grade',
            field=models.CharField(choices=[('adult', '성인'), ('teen', '청소년'), ('preferential', '우대')], default='adult', max_length=10),
        ),
    ]
