# Generated by Django 2.2.13 on 2020-06-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='type',
        ),
        migrations.AddField(
            model_name='screen',
            name='screen_type',
            field=models.CharField(choices=[('2D', '2D'), ('2Ds', '2D 자막'), ('3D', '3D')], default='2D', max_length=20),
        ),
        migrations.AddField(
            model_name='screen',
            name='seats_type',
            field=models.CharField(choices=[('A', 'A-type'), ('B', 'B-type'), ('C', 'C-type')], default='A', max_length=20),
        ),
    ]
