# Generated by Django 2.2.13 on 2020-07-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start_time']},
        ),
    ]
