# Generated by Django 2.2.14 on 2020-07-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_auto_20200707_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatgrade',
            name='grade',
            field=models.CharField(choices=[('adult', '성인'), ('teen', '청소년'), ('preferential', '우대')], default='adult', max_length=20),
        ),
    ]
