# Generated by Django 2.2.13 on 2020-06-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200630_1521'),
        ('theaters', '0002_auto_20200629_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], max_length=10)),
                ('col', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14)])),
                ('type', models.CharField(choices=[('impossible', '선택불가'), ('sit_apart', '띄어앉기석'), ('general', '일반'), ('disabled', '장애인석')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeatGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('adult', '성인'), ('youth', '청소년'), ('preferred', '우대')], max_length=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.Seat')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='reservation',
            field=models.ManyToManyField(through='theaters.SeatGrade', to='reservations.Reservation'),
        ),
        migrations.AddField(
            model_name='seat',
            name='screen',
            field=models.ManyToManyField(to='theaters.Screen'),
        ),
    ]
