# Generated by Django 2.2.13 on 2020-06-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0003_auto_20200630_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='reservation',
            field=models.ManyToManyField(related_name='seats', through='theaters.SeatGrade', to='reservations.Reservation'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='screen',
            field=models.ManyToManyField(related_name='seats', to='theaters.Screen'),
        ),
        migrations.AlterField(
            model_name='seatgrade',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_grades', to='reservations.Reservation'),
        ),
        migrations.AlterField(
            model_name='seatgrade',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_grades', to='theaters.Seat'),
        ),
    ]
