# Generated by Django 2.2.13 on 2020-07-01 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0004_auto_20200630_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='theaters.Screen'),
        ),
    ]
